### ISSUE TITLE
new jalidate incompatible with jdate

### ISSUE THREAD

**Issue by behroozam** [mehdisadeghi/jekyll-theme-mehdix-rtl#4] opened 2017-12-02 08:11 UTC
`Liquid Exception: Liquid error (line 20): invalid arguments or invalid Jalali date in /_layouts/post.html`
and date arguments in /post.html like this 
`{{ page.date | jdate: "%A %d %b %Y" | habify}}`

**Comment by mehdisadeghi** [comment] 2017-12-02 09:21
@behroozam please update your setup and try again. (remove Gemfile.lock and run `bundler install --force`) and let me know whether your problem is solved.

**Comment by behroozam** [comment] 2017-12-02 13:31
i removed gemfile.lock and bundler install --force but problem still remain 
  <span color=red>Liquid Exception: Liquid error (line 36): invalid arguments or invalid Jalali date in /_layouts/post.html</span>
my code is 
`<span class="date">{{ page.date | jdate: "%A %d %b %Y"}}</span>`

**Comment by mehdisadeghi** [comment] 2017-12-02 15:59
@behroozam which version of the gem are you using? You have to have a line like this in your `Gemfile`:

    gem "jekyll-theme-mehdix-rtl", "~> 0.1"

The latest version is `0.1.6` which will force installing a newer version of `jekyll-jalali` which should solve your problem.

**Comment by behroozam** [comment] 2017-12-10 11:36
i found problem . date in main theme dont have any response but in posts is ok .
jekyll jalali work fine 
i delete date from default theme

**Comment by mehdisadeghi** [comment] 2017-12-18 16:36
Since the problem is resolved I close this issue. Feel free to reopen if you still have some problems (or open a new one).

**Closed as completed by mehdisadeghi** 2017-12-18 16:36 UTC
